services:
  prometheus:
    image: prom/prometheus:v2.53.0
    ports:
      - "19090:9090"
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus-data:/prometheus
    labels:
      - "customization.image.slug=prometheus"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "18030:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=demo
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    labels:
      - "customization.image.slug=grafana"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.8.1
    ports:
      - "19100:9100"
    labels:
      - "customization.image.slug=prometheus"
    restart: unless-stopped

volumes:
  prometheus-data: {}
  grafana-data: {}

configs:
  prometheus_config:
    content: |
      global:
        scrape_interval: 15s

      scrape_configs:
        - job_name: prometheus
          static_configs:
            - targets: ["localhost:9090"]
        - job_name: node-exporter
          static_configs:
            - targets: ["node-exporter:9100"]
