version: wireops.v1
name: gitea
group: dev-tools
timeout: 3m
compose:
  remove_orphans: true
  force_pull: false
jobs:
  wait_running: true
worker:
  tags:
    - local
    - node
sync:
  interval: 5m
